// About dialog unit for the NppESPHome plugin.
// Contains the modal form that displays plugin version, copyright, project links,
// and applies Notepad++ dark mode colors/icons to the dialog.
unit NppESPHome.FormAbout;

interface

uses
  Winapi.Windows, System.SysUtils, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.StdCtrls, Vcl.ExtCtrls, NppPlugin, NppPluginForm,
  Vcl.VirtualImage, Vcl.ImageCollection, Vcl.BaseImageCollection;

type
  // About dialog shown from the NppESPHome plugin menu.
  // It inherits from TNppPluginForm so it can integrate with Notepad++ ownership,
  // dialog handling, and dark mode notifications.
  TFormAbout = class(TNppPluginForm)
    PanelMain: TPanel;
    LabelAppName1: TLabel;
    LabelVersion: TLabel;
    LabelCopyright: TLabel;
    ButtonOk: TButton;
    LabelAppName2: TLabel;
    LinkLabel1: TLinkLabel;
    LinkLabel2: TLinkLabel;
    LinkLabel3: TLinkLabel;
    VirtualImageLogo: TVirtualImage;
    ImageCollection: TImageCollection;

    // Form lifecycle
    procedure FormCreate(Sender: TObject);

    // Theme synchronization
    procedure ToggleDarkMode; override;

    // Link click handlers for the URLs exposed in the About dialog
    procedure LinkLabel1LinkClick(Sender: TObject; const Link: string;
      LinkType: TSysLinkType);
    procedure LinkLabel2LinkClick(Sender: TObject; const Link: string;
      LinkType: TSysLinkType);
    procedure LinkLabel3LinkClick(Sender: TObject; const Link: string;
      LinkType: TSysLinkType);
  end;

var
  // Global instance managed by the plugin/form infrastructure
  FormAbout: TFormAbout;

implementation

{$R *.dfm}

uses
  NppMessages, NppESPHome.Shared, Winapi.ShellAPI;

resourcestring
  // Localized caption prefix used for the plugin version label
  rsVersionAbout = 'Version';

{
  Purpose: Initializes the About dialog before it is shown.
  It reads the plugin version from the global Plugin instance and formats it as
  a standard four-part Windows version number: Major.Minor.Release.Build.
}
procedure TFormAbout.FormCreate(Sender: TObject);
begin
  with ParentPlugin do
    // Get*Version values are exposed by the NppPlugin base class.
    LabelVersion.Caption := Format('%s: %d.%d.%d.%d', [rsVersionAbout, GetMajorVersion, GetMinorVersion, GetReleaseNumber, GetBuildNumber]);

  // Static copyright text shown in the About dialog.
  LabelCopyright.Caption := 'Andrea Tiburzi (2025)';
end;

{
  Purpose: Opens the first hyperlink displayed in the About dialog.
  TLinkLabel passes the clicked URL in Link; ShellExecute delegates the actual
  navigation to the user's default browser.
}
procedure TFormAbout.LinkLabel1LinkClick(Sender: TObject; const Link: string;
  LinkType: TSysLinkType);
begin
  inherited;

  // Only process URL links. Other link types are ignored by this dialog.
  if LinkType = sltURL then
    ShellExecute(0, 'open', PChar(Link), nil, nil, SW_SHOWNORMAL);
end;

{
  Purpose: Opens the second hyperlink displayed in the About dialog.
  The implementation mirrors the first link handler so each label can be wired
  independently from the DFM designer.
}
procedure TFormAbout.LinkLabel2LinkClick(Sender: TObject; const Link: string;
  LinkType: TSysLinkType);
begin
  inherited;

  // SW_SHOWNORMAL lets Windows open the browser in its normal/restored state.
  if LinkType = sltURL then
    ShellExecute(0, 'open', PChar(Link), nil, nil, SW_SHOWNORMAL);
end;

{
  Purpose: Opens the third hyperlink displayed in the About dialog.
  Keeping a dedicated handler preserves the direct event bindings generated by
  the VCL form designer.
}
procedure TFormAbout.LinkLabel3LinkClick(Sender: TObject; const Link: string;
  LinkType: TSysLinkType);
begin
  inherited;

  // ShellExecute returns immediately; the About dialog remains open.
  if LinkType = sltURL then
    ShellExecute(0, 'open', PChar(Link), nil, nil, SW_SHOWNORMAL);
end;

{
  Purpose: Synchronizes the About dialog appearance with the current Notepad++
  theme. It updates the window icon and switches form/label colors between
  Notepad++ dark mode colors and the standard VCL light mode colors.
}
procedure TFormAbout.ToggleDarkMode;
var
  DarkModeColors: TNppDarkModeColors;
begin
  // Let the base TNppPluginForm apply its own dark mode handling first.
  inherited ToggleDarkMode;

  // Reuse the shared helper so the About form receives the same themed window
  // icon used by the rest of the plugin.
  AssignWindowIcon(Icon);

  if (ParentPlugin.IsDarkModeEnabled) then
  begin
    // Retrieve the active Notepad++ dark mode palette and apply it to this form.
    DarkModeColors := Default(TNppDarkModeColors);
    ParentPlugin.GetDarkModeColors(@DarkModeColors);

    // The About dialog uses standard labels, so colors are assigned explicitly.
    Self.Color := TColor(DarkModeColors.Background);
    Self.Font.Color := TColor(DarkModeColors.Text);
    LabelAppName1.Font.Color := TColor(DarkModeColors.Text);
    LabelAppName2.Font.Color := TColor(DarkModeColors.Text);
  end
  else
  begin
    // Restore standard VCL system colors for light mode.
    Self.Color := clBtnFace;
    Self.Font.Color := clWindowText;
    LabelAppName1.Font.Color := clWindowText;
    LabelAppName2.Font.Color := clWindowText;
  end;
end;


end.
